# Generated by Django 6.0.7 on 2026-07-16 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_discount_price_product_sku_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='needs_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(choices=[('admin', 'Admin'), ('catalogue', 'Catalogue')], default='admin', max_length=20),
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='products.product')),
            ],
        ),
    ]
