# Generated by Django 6.0.5 on 2026-07-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_needs_image_product_source_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(
                choices=[
                    ('INDOORS', 'Indoors'),
                    ('OUTDOORS', 'Outdoors'),
                    ('PARTS', 'Parts'),
                    ('RFSPORTS', 'MR Sports'),
                ],
                default='INDOORS',
                max_length=50,
            ),
        ),
    ]
