# Generated by Django 6.0.5 on 2026-07-19 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='module',
            field=models.CharField(blank=True, choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('rf_sports', 'RF Sports')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='products.product'),
        ),
        migrations.CreateModel(
            name='InquiryLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='products.inquiry')),
            ],
        ),
    ]
