# Generated by Django 6.0.5 on 2026-06-28 09:10

from django.db import migrations, models


def migrate_rfsports_to_mrsports(apps, schema_editor):
    """Convert existing products with RFSPORTS category to MRSPORTS."""
    Product = apps.get_model('products', 'Product')
    Product.objects.filter(category='RFSPORTS').update(category='MRSPORTS')


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('INDOORS', 'Indoors'), ('OUTDOORS', 'Outdoors'), ('PARTS', 'Parts'), ('MRSPORTS', 'MR Sports')], default='INDOORS', max_length=50),
        ),
        migrations.RunPython(migrate_rfsports_to_mrsports, reverse_code=migrations.RunPython.noop),
    ]
