# Generated by Django 6.0.5 on 2026-07-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_inquiry_email_inquiry_module_alter_inquiry_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquirylineitem',
            name='product_name',
            field=models.CharField(default='Unknown Product', max_length=255),
        ),
    ]
