# Generated by Django 6.0.5 on 2026-07-05 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parent_product',
            field=models.ForeignKey(blank=True, help_text='If set, this product is a variant of the parent product. Variants are hidden from category listings.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='products.product'),
        ),
    ]
