# Generated by Django 6.0.5 on 2026-07-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_inquirylineitem_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='module',
            field=models.CharField(blank=True, choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('mr_sports', 'MR Sports')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('INDOORS', 'Indoors'), ('OUTDOORS', 'Outdoors'), ('PARTS', 'Parts'), ('MRSPORTS', 'MR Sports')], default='INDOORS', max_length=50),
        ),
    ]
