# Generated by Django 6.0.5 on 2026-07-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_category'),
        ('products', '0009_alter_inquiry_module_alter_product_category'),
    ]

    operations = [
    ]
