# Generated by Django 6.0.5 on 2026-07-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_inquiry_inquiry_status_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='module',
            field=models.CharField(blank=True, choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('shreem_sports', 'Shreem Sports')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('INDOORS', 'Indoors'), ('OUTDOORS', 'Outdoors'), ('PARTS', 'Parts'), ('SHREEM_SPORTS', 'Shreem Sports')], default='INDOORS', max_length=50),
        ),
    ]
