# Generated by Django 6.0.5 on 2026-08-02 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_backfill_order_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='colour',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='colours',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ProductSizeSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_label', models.CharField(max_length=50)),
                ('age_min', models.PositiveIntegerField()),
                ('age_max', models.PositiveIntegerField()),
                ('size_dim1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('size_dim2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('size_unit', models.CharField(choices=[('cm', 'cm'), ('inch', 'inch')], default='cm', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_specs', to='products.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
