# Generated by Django 6.0.5 on 2026-08-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_orderitem_dimension_productclassspec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdimensionspec',
            name='component',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
