# Generated by Django 6.0.5 on 2026-08-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_productdimensionspec_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdimensionspec',
            name='height',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='productdimensionspec',
            name='length',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productdimensionspec',
            name='unit',
            field=models.CharField(choices=[('cm', 'cm'), ('inch', 'inch'), ('mm', 'mm'), ('ft', 'ft')], default='cm', max_length=10),
        ),
        migrations.AlterField(
            model_name='productdimensionspec',
            name='width',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
