# Generated by Django 6.0.5 on 2026-08-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_productdimensionspec_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdimensionspec',
            name='group_label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productdimensionspec',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
