"""
Django settings for little_fingers project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import warnings
from pathlib import Path
from urllib.parse import urlparse, unquote

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# ---------------------------------------------------------------------------
# Environment-driven configuration (fail-fast in production)
# ---------------------------------------------------------------------------

# DEBUG is read from the DJANGO_DEBUG env var and defaults to True so local
# development is never blocked. In production (Vercel) DJANGO_DEBUG=False must
# be set explicitly, and the app fails fast if required env vars are missing.
DEBUG = os.getenv("DJANGO_DEBUG", "True").strip().lower() in ("1", "true", "yes", "on")

REQUIRED_PROD_ENV_VARS = ("SECRET_KEY", "ADMIN_EMAIL", "ADMIN_PASSWORD")


def validate_production_env(debug=None, environ=None):
    """Fail fast when running in production mode without required env vars.

    Raises ImproperlyConfigured listing every missing variable so a deploy
    cannot silently start with insecure fallbacks. Never called when debug is
    truthy (local development logs a warning instead).
    """
    if debug is None:
        debug = DEBUG
    if debug:
        return
    environ = os.environ if environ is None else environ
    missing = [name for name in REQUIRED_PROD_ENV_VARS if not environ.get(name, "").strip()]
    if missing:
        raise ImproperlyConfigured(
            "Missing required environment variable(s) in production mode "
            f"(DJANGO_DEBUG=False): {', '.join(missing)}"
        )


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "").strip()
if not SECRET_KEY:
    if DEBUG:
        warnings.warn(
            "SECRET_KEY is not set. Using an insecure development fallback key. "
            "Set SECRET_KEY before deploying to production.",
            stacklevel=2,
        )
        SECRET_KEY = "django-insecure-dev-only-fallback-key-not-for-production"

# Fail fast at startup in production (no-op in local dev). Raises listing every
# missing required variable so a deploy can never start with insecure fallbacks.
validate_production_env()

# ALLOWED_HOSTS is an explicit allow-list read from env (comma-separated).
# Defaults include the production domains, localhost for local dev, and the
# Vercel preview pattern so preview deployments keep working.
_DEFAULT_ALLOWED_HOSTS = "akidsenterprise.com,www.akidsenterprice.com,localhost,127.0.0.1,.vercel.app"
ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("ALLOWED_HOSTS", _DEFAULT_ALLOWED_HOSTS).split(",")
    if host.strip()
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'products',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'little_fingers.middleware.SecurityHeadersMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'little_fingers.middleware.CsrfCookieBootstrapMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'little_fingers.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.parent / 'frontend' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'little_fingers.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

db_url = os.getenv("DATABASE_URL", "").strip()
if db_url and db_url.startswith("postgres"):
    url = urlparse(db_url)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': url.path[1:],
            'USER': unquote(url.username or ""),
            'PASSWORD': unquote(url.password or ""),
            'HOST': url.hostname,
            'PORT': url.port or 5432,
            'CONN_MAX_AGE': 600,  # Keep DB connections alive for 10 minutes (connection pooling)
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR.parent / 'frontend' / 'static']
STATIC_ROOT = BASE_DIR.parent / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Server-side caching (in-memory for Vercel/SQLite; swap to Redis for production PostgreSQL)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'akids-cache',
    }
}

# Use cached session backend — avoids DB hit on every request for session load
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR.parent / 'frontend' / 'media'

# Allow same-origin framing of pages/PDFs
X_FRAME_OPTIONS = 'SAMEORIGIN'

# ---------------------------------------------------------------------------
# Security hardening (SecurityMiddleware). HSTS / HTTPS-only cookie flags are
# gated on production (DEBUG=False) so local HTTP development keeps working.
# ---------------------------------------------------------------------------
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"

# Vercel terminates TLS at the edge and forwards `X-Forwarded-Proto: https`.
# Telling Django about this header makes request.is_secure() correct so HSTS /
# secure-cookie settings behave properly and no redirect loop is introduced.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Test database settings (avoid "database already exists" errors)
TEST = {
    'DATABASES': {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }
}

# Request timing middleware (at end so it only measures the view, not other middleware)
MIDDLEWARE.append('little_fingers.middleware.RequestTimingMiddleware')
